### ISSUE TITLE
Sample applications just keep black screen - Ubuntu 14.04

### ISSUE THREAD

**Issue by nguyendangminh** [google/gxui#35]
Hi there,

I built all samples successfully, but when running them it's just a black screen, like this:
![image](https://cloud.githubusercontent.com/assets/9614404/6746506/e546a118-cefb-11e4-97f3-798c5b27a71d.png)

I run it on Ubuntu 14.04, and:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 945GM x86/MMX/SSE2
OpenGL version string: 1.4 Mesa 10.3.2
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

**Comment by ben-clayton** [comment]
That's odd - do you know if any other OpenGL applications run successfully on this machine?

**Comment by nguyendangminh** [comment]
I can run glxgears (in mesa-utils package) successfully:
![image](https://cloud.githubusercontent.com/assets/9614404/6747512/f3e88d7e-cf0c-11e4-9374-4b5e59ec6613.png)

**Comment by phaikawl** [comment]
@nguyendangminh where is the black screen? Or is it just, no window appears?

**Comment by nguyendangminh** [comment]
Yep, just like the first image.

**Comment by sesteel** [comment]
@nguyendangminh Not to be insulting, but have you moved your console and other windows around to make sure it is not rendering behind another window?

**Comment by nguyendangminh** [comment]
Of course I did. I tried all the samples, not just the image_viewer.

**Comment by weberc2** [comment]
I'm seeing the same problem. Ubuntu 14.04 amd64.

**Comment by weberc2** [comment]
in sample/polygon, it hangs at `window.AddChild(image)`; it seems to be blocking--CPU is 0.

**Comment by weberc2** [comment]
I traced it down to line ~62 in drivers/gl/viewport.go: `wnd, err := glfw.CreateWindow(width, height, title, nil, nil)`

**Comment by weberc2** [comment]
Looks like it's this bug: https://github.com/glfw/glfw/issues/368 as explained by https://github.com/glfw/glfw/issues/373

**Comment by shurcooL** [comment]
That bug is fixed in GLFW 3.1.1, and there's a PR to update the Go bindings to that version at https://github.com/go-gl/glfw/pull/133.

Can you try that branch (https://github.com/go-gl/glfw/tree/glfw3.1.1) and see if it fixes the issue?

Our goal is to merge that branch within a day or two.

**Comment by weberc2** [comment]
@shurcooL Hmm, I tried that branch but I'm still not seeing any windows rendering on the screen...

**Comment by shurcooL** [comment]
@weberc2 That commit isn't on the `glfw3.1.1` branch. The commit should be glfw/glfw@e2a72536141989e2443442660d2cd362d10b9e70.

**Comment by weberc2** [comment]
@shurcooL Sorry, I'm not very git-savvy (`checkout -b glfw3.1.1` doesn't checkout the glfw3.1.1 branch; silly me, I guess). Anyway, that worked perfectly. Thanks!

**Comment by nguyendangminh** [comment]
Thanks @shurcooL, the commit works pretty well for me, all the samples run successfully.
